stages:
  preprocessing:
    cmd: python scripts/preprocessing.py
    outs:
    - data/preprocessed_fraudTest.csv
    - data/preprocessed_fraudTrain.csv
  training:
    cmd: python scripts/training.py
    deps:
    - data/preprocessed_fraudTest.csv
    - data/preprocessed_fraudTrain.csv
    - params.yaml
    - scripts/training.py
    - scripts/tuning.py
    outs:
    - model.pkl
