name: ML Training Pipeline
on: [workflow_dispatch, push]

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: file://${{ github.workspace }}/mlruns

    steps:
      # Checkout and setup
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install "dvc>=3.0.0"

      # Kaggle setup
      - name: Configure Kaggle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # DVC setup
      - name: Initialize DVC
        run: |
          dvc init --no-scm -f
          dvc config cache.type symlink

      # Run pipeline
      - name: Execute pipeline
        run: dvc repro

      # Archive results (updated to v4)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: |
            mlruns/
            model.pkl
          retention-days: 1
          compression-level: 9  # Better compression
